apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.3.9    # stable version
    helm:
      releaseName: grafana
      values: |
        adminUser: admin
        adminPassword: admin
        service:
          type: ClusterIP
          port: 3000
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Trino
                type: trinodb-trino-datasource
                access: proxy
                url: http://trino.trino:8080
                isDefault: true
                jsonData:
                  catalog: hive
                  schema: default
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards
        dashboardsConfigMaps:
          default: grafana-dashboard-transactions
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
