adminUser: admin
adminPassword: admin
service:
  type: ClusterIP
  port: 3000
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Trino
        type: trinodb-trino-datasource
        access: proxy
        url: http://trino.trino:8080
        isDefault: true
        jsonData:
          catalog: hive
          schema: default
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
dashboardsConfigMaps:
  default: grafana-dashboard-transactions
