# Airflow image
image:
  repository: apache/airflow
  tag: "2.9.0"
  pullPolicy: IfNotPresent

# Executor
executor: "CeleryExecutor"

# Airflow base configs
airflow:
  fernetKey: "your-fernet-key-here"   # generate with: openssl rand -base64 32
  secretKey: "super-secret-key"
  webserverSecretKey: "another-secret-key"
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET: "airflow-mysql-conn"  # refers to a Secret key (see below)

# Disable Postgres
postgresql:
  enabled: false

# Redis for CeleryExecutor
redis:
  enabled: true
  architecture: standalone

# Scheduler
scheduler:
  replicas: 1

# Webserver
web:
  replicas: 1
  service:
    type: ClusterIP
    port: 8080

# Worker pods
workers:
  replicas: 2

# DAGs config
dags:
  persistence:
    enabled: false # switch to PVC/S3/git-sync for prod
  path: /opt/airflow/dags

# Logs persistence
logs:
  persistence:
    enabled: false

# Ingress
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: Prefix
