executor: LocalExecutor
web:
  service:
    type: ClusterIP
    port: 8080

airflow:
  image:
    repository: apache/airflow
    tag: 2.6.3

  fernetKey: "change_me_fernet_key"
  defaultUser:
    enabled: true
    username: admin
    password: admin
    role: Admin
    email: admin@example.com

  connections:
    - id: mysql_conn
      type: mysql
      host: mysql.devproject
      login: app
      password: apppass
      schema: appdb
    - id: minio_conn
      type: s3
      extra: |
        {
          "aws_access_key_id": "minioadmin",
          "aws_secret_access_key": "minioadmin",
          "host": "http://minio.minio:9000",
          "region_name": "us-east-1",
          "config_kwargs": {"s3": {"addressing_style": "path"}}
        }
    - id: trino_default
      type: trino
      host: trino.trino
      schema: default
      port: 8080
