# Airflow image
image:
  repository: apache/airflow
  tag: "2.9.0"
  pullPolicy: IfNotPresent

# Executor - keep it simple
executor: "LocalExecutor"

# Airflow base configs
airflow:
  fernetKey: "your-fernet-key-here"   # generate with: openssl rand -base64 32
  secretKey: "super-secret-key"
  webserverSecretKey: "another-secret-key"
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__EXECUTOR: "LocalExecutor"

#  Enable Postgres (Airflow metadata DB)
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: gp2   # force AWS gp2 storage class

#  Disable Redis (not needed for LocalExecutor)
redis:
  enabled: false

# Scheduler
scheduler:
  replicas: 1

# Webserver
web:
  replicas: 1
  service:
    type: ClusterIP
    port: 8080

#  Disable Workers (only needed for CeleryExecutor)
workers:
  enabled: false

#  Disable Triggerer (optional, keeps demo light)
triggerer:
  enabled: false

# DAGs config (for demo, mount via ConfigMap or S3/git-sync in prod)
dags:
  persistence:
    enabled: false
  path: /opt/airflow/dags

# Logs persistence (disable for demo)
logs:
  persistence:
    enabled: false

# Ingress (disabled for demo, you can port-forward)
ingress:
  enabled: false

      paths:
        - path: /
          pathType: Prefix
