image:
  repository: apache/airflow
  tag: "2.9.0"
  pullPolicy: IfNotPresent

# Executor - simplest for demo
executor: "LocalExecutor"

airflow:
  fernetKey: "your-fernet-key-here"   # openssl rand -base64 32
  secretKey: "super-secret-key"
  webserverSecretKey: "another-secret-key"
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  connections:
    - id: mysql_conn
      type: mysql
      host: mysql.devproject
      schema: bankappdb
      login: root
      password: "Test@123"    
      port: 3306
    - id: minio_conn
      type: s3
      extra: |
        {
          "aws_access_key_id": "minioadmin",
          "aws_secret_access_key": "minioadmin",
          "host": "http://minio.minio:9000",
          "region_name": "us-east-1"
        }

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: gp3-csi
      size: 8Gi

# Disable everything not needed for LocalExecutor
redis:
  enabled: false
triggerer:
  enabled: false
logs:
  persistence:
    enabled: false   # ✅ no PVCs for logs

scheduler:
  replicas: 1

web:
  replicas: 1
  service:
    type: ClusterIP
    port: 8080

# Mount DAGs from ConfigMap
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: false

extraVolumes:
  - name: airflow-dags
    configMap:
      name: airflow-dags

extraVolumeMounts:
  - name: airflow-dags
    mountPath: /opt/airflow/dags
