apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org'
    chart: airflow
    targetRevision: 1.13.0
    helm:
      releaseName: airflow
      values: |
        executor: "CeleryExecutor"
        workers:
          replicas: 2
        service:
          type: ClusterIP
        web:
          port: 8080
          service:
            type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
