apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: minio
    targetRevision: "17.0.21"
    helm:
      releaseName: minio
      values: |
        auth:
          rootUser: admin
          rootPassword: minio123
        defaultBuckets: bankapp,datalake
        service:
          type: ClusterIP
          port: 9000
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
