apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.13.0
    helm:
      releaseName: airflow
      values: |
        executor: "LocalExecutor"
        postgresql:
          enabled: false
        redis:
          enabled: false
        triggerer:
          enabled: false
        workers:
          enabled: false
        externalDatabase:
          type: mysql
          host: mysql.devproject.svc.cluster.local
          port: 3306
          user: root
          passwordSecret:
            name: bankapp-db-externalsecret
            key: Test@123
          database: bankappdb
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


